import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Plus, Book } from 'lucide-react';
import { type Subject, SubjectSchema, SUBJECT_TYPES } from '../types';

import { Modal } from '../../../components/common/Modal';
import { Input } from '../../../components/common/Input';
import { Select } from '../../../components/common/Select'; // Assuming exists

// Form Schema can be inferred or reused if strict matching
const CreateSubjectSchema = SubjectSchema.omit({ id: true });
type SubjectFormValues = z.input<typeof CreateSubjectSchema>;

interface SubjectManagerProps {
  subjects: Subject[];
  addSubject: (data: Partial<Subject>) => Promise<any>;
  loading: boolean;
}

export const SubjectManager: React.FC<SubjectManagerProps> = ({ subjects, addSubject, loading }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { register, handleSubmit, reset, formState: { errors } } = useForm<SubjectFormValues>({
    resolver: zodResolver(CreateSubjectSchema), // ID is generated by backend
    defaultValues: {
      type: 'Theory'
    }
  });

  const onSubmit = async (data: SubjectFormValues) => {
    await addSubject(data);
    setIsModalOpen(false);
    reset();
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-4 sm:p-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-4 sm:mb-6">
        <div>
           <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
             <Book className="w-5 h-5 text-blue-500" />
             Subjects
           </h2>
           <p className="text-sm text-gray-500">Manage academic subjects list</p>
        </div>
        <button
          onClick={() => setIsModalOpen(true)}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add Subject
        </button>
      </div>

      <div className="overflow-hidden border border-gray-200 dark:border-gray-700 rounded-lg">
        <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead className="bg-gray-50 dark:bg-gray-900/50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Code</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
            </tr>
          </thead>
          <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            {subjects.length === 0 ? (
                <tr>
                    <td colSpan={3} className="px-6 py-8 text-center text-gray-500 text-sm">
                        No subjects found. Add one to get started.
                    </td>
                </tr>
            ) : (
                subjects.map((subject) => (
                <tr key={subject.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                    {subject.name}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                    <span className="px-2 py-1 bg-gray-100 dark:bg-gray-700 rounded text-xs font-mono">
                        {subject.code}
                    </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {subject.type}
                    </td>
                </tr>
                ))
            )}
          </tbody>
        </table>
      </div>

      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Add New Subject"
      >
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <Input
            label="Subject Name"
            placeholder="e.g. Mathematics"
            error={errors.name?.message}
            {...register('name')}
          />
          <Input
            label="Subject Code"
            placeholder="e.g. MATH101"
            error={errors.code?.message}
            {...register('code')}
          />
          <Select
            label="Type"
            error={errors.type?.message}
            {...register('type')}
          >
            {SUBJECT_TYPES.map((type) => (
                <option key={type} value={type}>{type}</option>
            ))}
          </Select>
          
          <div className="flex justify-end gap-3 mt-6">
            <button
               type="button"
               onClick={() => setIsModalOpen(false)}
               className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
                Cancel
            </button>
            <button
               type="submit"
               disabled={loading}
               className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 disabled:opacity-50"
            >
                {loading ? 'Saving...' : 'Save Subject'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
};
