import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { ReportHeader } from './pdf-components';

const styles = StyleSheet.create({
    page: { padding: 30, fontFamily: 'Helvetica' },
    section: { marginVertical: 10, padding: 10, borderBottomWidth: 1, borderBottomColor: '#eee' },
    infoGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 20 },
    infoItem: { width: '50%', marginBottom: 5 },
    label: { fontSize: 9, color: '#666', marginBottom: 2 },
    value: { fontSize: 10, fontWeight: 'bold' },
    table: { marginTop: 20 },
    tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 8 },
    tableHeader: { backgroundColor: '#f9f9f9', borderBottomWidth: 2, borderBottomColor: '#3B82F6' },
    col1: { flex: 2 },
    col2: { flex: 1, textAlign: 'right' },
    totalSection: { marginTop: 20, alignItems: 'flex-end', paddingTop: 10, borderTopWidth: 2, borderTopColor: '#3B82F6' },
    totalLabel: { fontSize: 12, fontWeight: 'bold' },
    footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 8, color: '#aaa' },
});

interface FeeSlipData {
    student: { name: string; rollNumber: string; admissionNumber: string; class: string; section: string };
    ledger: {
        totalAmount: number;
        paidAmount: number;
        pendingAmount: number;
        dueDate?: string;
    };
    transactions: Array<{ date: string; amount: number; method: string; status: string }>;
}

export const FeeSlipDocument: React.FC<{ data: FeeSlipData }> = ({ data }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <ReportHeader title="FEE CHALLAN / RECEIPT" />

            <View style={styles.section}>
                <View style={styles.infoGrid}>
                    <View style={styles.infoItem}>
                        <Text style={styles.label}>Student Name</Text>
                        <Text style={styles.value}>{data.student.name}</Text>
                    </View>
                    <View style={styles.infoItem}>
                        <Text style={styles.label}>Admission No / Roll No</Text>
                        <Text style={styles.value}>{data.student.admissionNumber} / {data.student.rollNumber}</Text>
                    </View>
                    <View style={styles.infoItem}>
                        <Text style={styles.label}>Class & Section</Text>
                        <Text style={styles.value}>{data.student.class} - {data.student.section}</Text>
                    </View>
                    <View style={styles.infoItem}>
                        <Text style={styles.label}>Date of Issue</Text>
                        <Text style={styles.value}>{new Date().toLocaleDateString()}</Text>
                    </View>
                </View>
            </View>

            <View style={styles.table}>
                <View style={[styles.tableRow, styles.tableHeader]}>
                    <Text style={[styles.col1, { fontWeight: 'bold', fontSize: 10 }]}>Description</Text>
                    <Text style={[styles.col2, { fontWeight: 'bold', fontSize: 10 }]}>Amount (INR)</Text>
                </View>
                <View style={styles.tableRow}>
                    <Text style={styles.col1}>Total Fees Assigned</Text>
                    <Text style={styles.col2}>{data.ledger.totalAmount.toFixed(2)}</Text>
                </View>
                <View style={styles.tableRow}>
                    <Text style={styles.col1}>Total Paid Amount</Text>
                    <Text style={styles.col2}>{data.ledger.paidAmount.toFixed(2)}</Text>
                </View>
                {data.transactions.slice(0, 3).map((t, i) => (
                    <View style={styles.tableRow} key={i}>
                        <Text style={styles.col1}>Recent Payment ({new Date(t.date).toLocaleDateString()})</Text>
                        <Text style={styles.col2}>- {t.amount.toFixed(2)}</Text>
                    </View>
                ))}
            </View>

            <View style={styles.totalSection}>
                <Text style={styles.totalLabel}>Pending Amount: INR {data.ledger.pendingAmount.toFixed(2)}</Text>
                {data.ledger.dueDate && (
                    <Text style={[styles.label, { marginTop: 5, color: '#ef4444' }]}>Due Date: {new Date(data.ledger.dueDate).toLocaleDateString()}</Text>
                )}
            </View>

            <View style={{ marginTop: 40 }}>
                <Text style={{ fontSize: 9, color: '#666', fontStyle: 'italic' }}>
                    Note: This is a computer generated document and does not require a physical signature.
                </Text>
            </View>

            <Text style={styles.footer}>
                Generated by Sanchalan Finance Module - {new Date().toLocaleDateString()}
            </Text>
        </Page>
    </Document>
);
