import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { ReportCardHeader, MarksTable } from './pdf-components';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  studentInfo: {
    marginTop: 20,
    marginBottom: 20,
    padding: 10,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 4,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  label: {
    fontSize: 10,
    fontWeight: 'bold',
    width: 100,
  },
  value: {
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaa',
  },
});

interface ReportData {
  student: { name: string; rollNumber: string; class: string; section: string };
  exam: { name: string; year: string };
  marks: Array<{ subject: string; max: number; obtained: number; grade: string }>;
  summary: { totalMax: number; totalObtained: number; percentage: number; finalGrade: string };
}

interface ReportCardDocumentProps {
  data: ReportData;
}

export const ReportCardDocument: React.FC<ReportCardDocumentProps> = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <ReportCardHeader />

      <View style={styles.studentInfo}>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Student Name:</Text>
          <Text style={styles.value}>{data.student.name}</Text>
        </View>
        <View style={styles.infoRow}>
            <Text style={styles.label}>Roll No:</Text>
            <Text style={styles.value}>{data.student.rollNumber}</Text>
        </View>
        <View style={styles.infoRow}>
            <Text style={styles.label}>Class:</Text>
            <Text style={styles.value}>{data.student.class} - {data.student.section}</Text>
        </View>
        <View style={styles.infoRow}>
            <Text style={styles.label}>Exam:</Text>
            <Text style={styles.value}>{data.exam.name} ({data.exam.year})</Text>
        </View>
      </View>

      <MarksTable data={data.marks} />

      <View style={{ marginTop: 20, alignItems: 'flex-end' }}>
          <Text style={{ fontSize: 12, fontWeight: 'bold' }}>Total: {data.summary.totalObtained} / {data.summary.totalMax}</Text>
          <Text style={{ fontSize: 12, fontWeight: 'bold' }}>Percentage: {data.summary.percentage}%</Text>
          <Text style={{ fontSize: 12, fontWeight: 'bold' }}>Grade: {data.summary.finalGrade}</Text>
      </View>

      <Text style={styles.footer}>
        Generated by Sanchalan - {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);
